### ISSUE TITLE
开发环境下运行项目，不知为何页面一直白屏刷新，也没有报错。

### ISSUE THREAD

**Issue by yorhasaber** [imsyy/SPlayer#1]
![image](https://user-images.githubusercontent.com/62880817/213134297-33784d51-4c65-4aae-ba7d-732c9d78d891.png)
资源加载好像没有成功，而且特别慢
![image](https://user-images.githubusercontent.com/62880817/213134613-0f3a099c-e979-410b-b908-0e9999366ef7.png)

**Comment by imsyy** [comment]
我这边无法复现，pnpm build 能正常构建吗？

**Comment by yorhasaber** [comment]
试了一下pnpm build 之后部署在 搭建的本地 express 服务器是可以正常打开页面的。但是开发环境下 pnpm dev 就会出现上述问题。
