### ISSUE TITLE
每日推荐没有同步更新

### ISSUE THREAD

**Issue by kokojacket** [imsyy/SPlayer#101]
### 是网页端还是客户端

网页端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

不知

### 当前版本

2.0.0-beta.5

### 具体信息

web
![image](https://github.com/imsyy/SPlayer/assets/74887370/7966f1e8-4c07-4e2b-9a12-9f5be8ca4de7)
网易云客户端
![image](https://github.com/imsyy/SPlayer/assets/74887370/661d45c7-1cf2-4ab6-9702-dae6028f1d9c)

**Comment by imsyy** [comment]
试试可以不

**Comment by kokojacket** [comment]
emmm，应该如何试，我是非技术人员，不会操作hhhhh，只是会简单的部署docker和构建小的镜像。。

**Comment by imsyy** [comment]
拉取下最新分支，然后重新构建下镜像

**Comment by kokojacket** [comment]
我是威联通nas上部署，没法使用git命令，然后手动下载zip解压后再构建，一直都没成功过，只能等大佬您更新dockerhub的镜像了
![image](https://github.com/imsyy/SPlayer/assets/74887370/e9ccbfad-ba2a-4de2-8e4b-9a154b9ae7ea)

**Comment by imsyy** [comment]
Docker Hub 已更新，重新部署下吧

**Comment by kokojacket** [comment]
好的，大佬效率真高~！因为重新登录临时刷新了今日推荐，我明早再检查一下~
