### ISSUE TITLE
搜索框无法输入空格

### ISSUE THREAD

**Issue by fuyn101** [imsyy/SPlayer#102]
### 是网页端还是客户端

客户端

### 当前系统环境

Win11

### 当前 Node.js 及 npm 版本

18.16/9.67（我不知道）

### 当前版本

V2.0.0-beta5

### 具体信息

用得是Action中的 3dbdf3e6136d929e4787cadfff54f8c11178a5cc

[PixPin_2023-12-21_17-00-01](https://github.com/imsyy/SPlayer/assets/151902446/57dce571-7a22-43ca-a2ad-83ad63b4dc55)

**Comment by imsyy** [comment]
故意为之的，否则会出现一些奇怪的小问题，等后面看看再调整吧

**Comment by imsyy** [comment]
已修复
