### ISSUE TITLE
添加功能：调用服务器的音箱播放歌曲

### ISSUE THREAD

**Issue by huaimi123** [imsyy/SPlayer#104]
### 希望添加什么功能？

调用服务器的音箱播放歌曲

### 具体信息

假设我在linux设备上使用docker来安装SPlayer，能不能通过调用linux上的VLC播放器接口（或者内置一个VLC，MPD之类的）来实现 手机访问hocalhost:7899网页点歌，linux音箱放歌的效果。
https://github.com/shaonianzhentan/ha_cloud_music
这个是homeassistant云音乐，我不是专业的，不知道能不能参考。这个是可以在homeassistant里添加云音乐和VLC，然后可以实现上述 手机点歌linux音箱放歌效果。

**Comment by imsyy** [comment]
抱歉，这个功能与本项目不相关，且无法实现
