### ISSUE TITLE
希望添加的功能

### ISSUE THREAD

**Issue by blogclub** [imsyy/SPlayer#111]
### 希望添加什么功能？

1.点击歌单或专辑上的播放图标就播放里面的音乐  
2.侧边栏“创建的歌单”、”收藏的歌单”下的歌单列表希望有个封面展示，类似spotify那样

**Comment by imsyy** [comment]
第一项已支持 https://github.com/imsyy/SPlayer/commit/a341a69d48a0e69af2389d13c70b21c2fadc1334
第二项封面展示还在考虑中，感觉和界面不太搭

**Comment by imsyy** [comment]
已支持配置是否展示封面
