### ISSUE TITLE
音乐标签影响播放

### ISSUE THREAD

**Issue by zzsail** [imsyy/SPlayer#113]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v18.15

### 当前版本

v2.0.0 beta5

### 具体信息

刚下载的歌曲播放会显示不支持的音乐格式无法播放，其音乐标签如左图
在使用音乐标签重新编辑后的标签如右图，就可以正常播放。不知道这是什么原因
![Snipaste_2023-12-30_13-22-51](https://github.com/imsyy/SPlayer/assets/103939610/447aec15-5b09-437a-a201-3b8edae927ab)![Snipaste_2023-12-30_13-23-00](https://github.com/imsyy/SPlayer/assets/103939610/d6a18bfd-89a3-4653-b260-4982263d6c5d)

**Comment by imsyy** [comment]
能提供下音乐源文件吗

**Comment by zzsail** [comment]
> 能提供下音乐源文件吗

发到你的邮箱了

**Comment by imsyy** [comment]
> > 能提供下音乐源文件吗
> 
> 发到你的邮箱了
> 

好的，稍后我看看

**Comment by imsyy** [comment]
实在是无法定位具体问题，感觉应该是这个音频文件有问题

**Comment by imsyy** [comment]
@zzsail 已修复，可以试下 v2.0.1
