### ISSUE TITLE
随机播放模式下上一曲和下一曲不符合实际播放的顺序

### ISSUE THREAD

**Issue by WoodsTide** [imsyy/SPlayer#114]
### 是网页端还是客户端

客户端

### 当前系统环境

Win10

### 当前 Node.js 及 npm 版本

v18.19.0/10.2.5

### 当前版本

v2.0.0-beta.5

### 具体信息

如题

**Comment by imsyy** [comment]
随机播放目前采用的是 `js` 原生的伪随机，当为随机播放模式时，将随机生成一个播放索引。所以，播放列表上的歌曲顺序并不反映真实的随机播放顺序
