### ISSUE TITLE
【遇到问题】本地音频文件歌词显示错误

### ISSUE THREAD

**Issue by subframe7536** [imsyy/SPlayer#121]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v18.16.0 /v9.6.7

### 当前版本

v2.0.0

### 具体信息

同时间戳的翻译歌词不能识别为同一句
![image](https://github.com/imsyy/SPlayer/assets/78338239/2e447811-0aff-4b10-be5b-46144694ffe6)

**Comment by imsyy** [comment]
会在下个版本做出修复

**Comment by imsyy** [comment]
@subframe7536 已修复，可以试下 v2.0.1
