### ISSUE TITLE
【遇到问题】上传歌曲错误

### ISSUE THREAD

**Issue by snhun** [imsyy/SPlayer#126]
### 是网页端还是客户端

客户端

### 当前系统环境

WIN11

### 当前 Node.js 及 npm 版本

0

### 当前版本

2.0.1

### 具体信息

如图，上传歌曲失败，一直卡着不动
![image](https://github.com/imsyy/SPlayer/assets/5186603/723e528f-290f-45f5-9af8-ac49e78362f9)

**Comment by imsyy** [comment]
不建议使用上传功能，接口很不稳定
