### ISSUE TITLE
无法连接到自己搭建的api

### ISSUE THREAD

**Issue by shenyunuoyan** [imsyy/SPlayer#138]
### 是网页端还是客户端

网页

### 当前系统环境

宝塔

### 当前 Node.js 及 npm 版本

v16.20.2/8.19.4

### 当前版本

v1

### 具体信息

![api](https://github.com/imsyy/SPlayer/assets/106127365/264676d6-4b56-4c74-b1ff-a63c4ea6eac4)
这是api，可以使用的，
![peizhi](https://github.com/imsyy/SPlayer/assets/106127365/0a70a79d-b9f7-4b4f-8958-6201011b9f6e)
这是配置的
![jiemian](https://github.com/imsyy/SPlayer/assets/106127365/ff869989-4997-4e83-b2a1-9000227ba27b)
然后ye'mia页面还是无法访问

**Comment by imsyy** [comment]
请提供控制台报错

试下 https

**Comment by shenyunuoyan** [comment]
看了下控制台，找到问题了，没有重新编译打包，重新编译打包后正常访问
