### ISSUE TITLE
有个疑惑，为什么linux下点击关闭窗口按钮，需要获取root权限？

### ISSUE THREAD

**Issue by student-ice** [imsyy/SPlayer#139]
### 是网页端还是客户端

客户端

### 当前系统环境

deepin v23 beta2

### 当前 Node.js 及 npm 版本

v18.17.1

### 当前版本

v2.0.0-beta5

### 具体信息

此时关闭这个鉴权窗口，程序可以正常退出
![image](https://github.com/imsyy/SPlayer/assets/59855569/f613d56f-231c-441d-9710-a2638f39f7db)

**Comment by imsyy** [comment]
应该是 electron 或者 deepin 的问题，我这边没做任何申请 root 权限的操作

**Comment by student-ice** [comment]
> 应该是 electron 或者 deepin 的问题，我这边没做任何申请 root 权限的操作

不知其他Linux发行版有没有这种现象
