### ISSUE TITLE
不知道登录了谁的账号

### ISSUE THREAD

**Issue by student-ice** [imsyy/SPlayer#141]
### 是网页端还是客户端

客户端

### 当前系统环境

deepin v23 beta2

### 当前 Node.js 及 npm 版本

v18.17.1

### 当前版本

v2.0.0-beta5

### 具体信息

今天打开SPlayer就发现不知道登录了谁的账号，我好像也没在这个软件登录过账号啊
是不是打包带了什么东西进来
还有vip ((
![image](https://github.com/imsyy/SPlayer/assets/59855569/78482bef-11d3-488a-933e-11eb9f31d988)

**Comment by itzj90** [comment]
大佬，能在服务端登录帐号吗
