### ISSUE TITLE
登录账号时 ; n-tabs-tab 组件的小Bug

### ISSUE THREAD

**Issue by Heartworm97** [imsyy/SPlayer#144]
### 是网页端还是客户端

网页端 / 客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v18.16.0

### 当前版本

v2.0.3

### 具体信息

第一次打开时，n-tabs-tab 是缩小不完整的现象，当我来回切换时，才恢复正常现象。每次打开登录窗口界面都是如此。
![QQ截图20240206001315](https://github.com/imsyy/SPlayer/assets/111258434/1b71d88d-4376-4148-94d2-82ea638f9607)

**Comment by Heartworm97** [comment]
![QQ截图20240206001302](https://github.com/imsyy/SPlayer/assets/111258434/fb846130-bab2-4b94-be8f-c195a3120588)
候补图片

**Comment by imsyy** [comment]
https://github.com/tusen-ai/naive-ui/issues/5569

**Comment by imsyy** [comment]
已解决该问题
