### ISSUE TITLE
关于粗体字体的问题

### ISSUE THREAD

**Issue by Yos-X** [imsyy/SPlayer#156]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

Node.js v18.13.0 / npm 9.6.7

### 当前版本

v2.0.5

### 具体信息

SPlayer中使用了许多粗体，但是它们似乎并不是字体的粗体，并且观察到作者的博客也有类似的现象。
比如，同样是“关于本站”四个字：
![粗体](https://github.com/imsyy/SPlayer/assets/97019070/f5c9bb51-b598-4271-a03a-b3066b34a026)
![强行加粗](https://github.com/imsyy/SPlayer/assets/97019070/6f976822-282a-4921-beff-1eaf170b2e0d)
明显可以看出第一种是字体设计时的粗体，而第二种则类似于“强行加粗”。
大量地，在SPlayer中也有这样的现象：
![SPlayer](https://github.com/imsyy/SPlayer/assets/97019070/78a3c567-94be-4537-b54e-35453bbe4d78)
强行加粗的字体效果并不是很好，希望作者后续可以优化一下？

**Comment by Yos-X** [comment]
使用的是 HarmonyOS Sans 的 Regular？
![image](https://github.com/imsyy/SPlayer/assets/97019070/68bcb841-1ab7-4aec-80ea-787b3e2d6219)
但是后期又将其字重改为 bold 导致的
![image](https://github.com/imsyy/SPlayer/assets/97019070/8729f730-e1c7-4843-97e2-02f103787c8b)

**Comment by imsyy** [comment]
主要是字体cdn用的是B站的，当初就只引用了一个，这一点确实可以优化下

**Comment by Yos-X** [comment]
2.0.6 好像并没有什么变化，部分字体仍是强行加粗的效果……
![image](https://github.com/imsyy/SPlayer/assets/97019070/d40dc484-dbd8-447a-9f30-82305c41935d)
另：更新后，已尝试重置/重装

**Comment by imsyy** [comment]
后续会把自定义字体加上
