### ISSUE TITLE
网页端无法正常访问

### ISSUE THREAD

**Issue by liyixin21** [imsyy/SPlayer#158]
### 是网页端还是客户端

网页端

### 当前系统环境

ubuntu 22.04.4 LTS

### 当前 Node.js 及 npm 版本

v12.22.9/10.2.4

### 当前版本

v2.0.5

### 具体信息

![截图 2024-04-14 05-33-39](https://github.com/imsyy/SPlayer/assets/76620207/642b8533-2741-4342-a8be-c796ae97b500)
api是正常的
![截图 2024-04-14 05-34-35](https://github.com/imsyy/SPlayer/assets/76620207/9b9063ce-a375-4e5f-ac21-9ba1b97e2b8c)
这个是配置文件
![截图 2024-04-14 05-43-37](https://github.com/imsyy/SPlayer/assets/76620207/b8e00a9a-763a-45f8-bc6e-4e819192dbc4)
网页端一直提示网络连接错误
![截图 2024-04-14 05-46-25](https://github.com/imsyy/SPlayer/assets/76620207/2b347380-cddc-42af-82b3-4f5bf55bfd00)
但是客户端正常

[localhost-1713044881712.log](https://github.com/imsyy/SPlayer/files/14968730/localhost-1713044881712.log)
这是控制台文件

**Comment by imsyy** [comment]
请认真阅读文档，api 不是部署 meting
