### ISSUE TITLE
发版时能否也同时发布打包好的安装包呢？

### ISSUE THREAD

**Issue by LS-King** [imsyy/SPlayer#16]
如题

**Comment by imsyy** [comment]
由于目前暂时未使用 `Electron`，所以目前只有在线版本，没有安装包，不过目前支持 `PWA`，可以通过浏览器将其独立添加到桌面

**Comment by Dev-Wiki** [comment]
> 由于目前暂时未使用 `Electron`，所以目前只有在线版本，没有安装包，不过目前支持 `PWA`，可以通过浏览器将其独立添加到桌面

是否可支持 docker 安装部署? @imsyy
