### ISSUE TITLE
请问首页加载不出来，也登录不了是因为在线版本将转为维护模式的原因吗？

### ISSUE THREAD

**Issue by snfcx** [imsyy/SPlayer#163]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

无

### 当前版本

 v2.0.7

### 具体信息

![image](https://github.com/imsyy/SPlayer/assets/55078254/e57f7eae-623f-447d-98c4-1cb110a452af)
之前可以正常使用重装了系统之后就不行了正好在这个时间上想确认一下，谢谢！

**Comment by snfcx** [comment]
> 开启软件时有报错吗？是端口占用了吗

![image](https://github.com/imsyy/SPlayer/assets/55078254/ccc41e16-14a9-4414-8322-3c911b0dd906)
![{F2090450-6ABF-466d-9A1B-99F7393B72B1}](https://github.com/imsyy/SPlayer/assets/55078254/cb4db47e-31b9-42c3-9107-db4db9e364fe)
开启软件的时候没有报错，直接到主界面加载不出来
打开软件的时候网页端也可以正常打开，只看到7899这个端口。

**Comment by imsyy** [comment]
可以 ctrl+shift+i 打开控制台看下有没有报错

**Comment by snfcx** [comment]
> 可以 ctrl+shift+i 打开控制台看下有没有报错

![image](https://github.com/imsyy/SPlayer/assets/55078254/57290b1e-7a7b-41da-9c1e-83fd9b0a7b08)
请您帮忙看看，谢谢！

**Comment by snfcx** [comment]
找到原因了！！！是火绒6.0版本的原因（之前用的原来的老版本没有问题）
参考https://bbs.huorong.cn/forum.php?mod=viewthread&tid=138805&highlight=YesPlayMusic
在Web扫描功能下添加信任程序即可
感谢开发者这个软件真的很美很好用！
