### ISSUE TITLE
歌词模式下窗口无法拖动

### ISSUE THREAD

**Issue by dreamsmaner** [imsyy/SPlayer#168]
### 是网页端还是客户端

客户端

### 当前系统环境

Win10 x64

### 当前 Node.js 及 npm 版本

N/A

### 当前版本

v2.0.9

### 具体信息

播放时，如果点击左下角专辑图片，会进入歌词模式（非全屏），这时候整个软件窗口就没法拖动了，必须退出歌词模式才可以。

**Comment by yebei199** [comment]
我也是
