### ISSUE TITLE
打开软件后就全白

### ISSUE THREAD

**Issue by HEW666** [imsyy/SPlayer#169]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v20.11.1  10.2.4

### 当前版本

v2.0.9

### 具体信息

安装好之后运行
![anzhuanghoubaocuo](https://github.com/imsyy/SPlayer/assets/67474081/0f17a9ed-b82e-4f8d-8d12-d3159d319425)

双击打开就这样
![shuangjidakaxianshi](https://github.com/imsyy/SPlayer/assets/67474081/1e0e00a1-0f13-4347-9be6-4d42ebbcace7)

**Comment by HEW666** [comment]
![image](https://github.com/imsyy/SPlayer/assets/67474081/e207f122-0d6f-4558-89a0-3173acc6111a)

**Comment by imsyy** [comment]
端口占用，或者更换启动端口
