### ISSUE TITLE
遇到一些问题，不知道算不算bug；无法显示评论

### ISSUE THREAD

**Issue by loongkc** [imsyy/SPlayer#171]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前 Node.js 及 npm 版本

v20.10.0/v10.2.5

### 当前版本

v2.0.9

### 具体信息

1. 在播放界面右上有两个按键，一个全屏，一个退回页面
2. 点击全屏的按钮，这时退回按钮就没了，只有一个取消全屏
3.按esc，会窗口化，退出全屏，但是此时按键任然只有一个，是退出全屏，且按了功能是全屏，回到2的状态
![image](https://github.com/imsyy/SPlayer/assets/103474466/32640631-b1e6-452c-a569-aad9eafb8107)
![image](https://github.com/imsyy/SPlayer/assets/103474466/22118f2e-f528-4bc2-a49b-954478901139)
![image](https://github.com/imsyy/SPlayer/assets/103474466/5f2264db-e400-46f3-a039-26bf182528f7)

还有一个问题是我的评论加载不出来，不知道为什么，试了好几天了
![image](https://github.com/imsyy/SPlayer/assets/103474466/8b5d5c4d-a24b-456c-b7a5-8578697c5cc9)

**Comment by imsyy** [comment]
1. 全屏那个确实是个bug，但是关闭按钮不是的，本意是如果在全屏状态下如果关闭了歌词界面的话，就无法退出全屏了（ 不考虑 esc 的话 ）
2. 评论的问题可以打开控制台看看报错（ ctrl+shift+i ）

**Comment by imsyy** [comment]
![image](https://github.com/imsyy/SPlayer/assets/42232682/dd703fc0-1da2-4385-ac7b-440df0c66e25)
我这边测试评论正常

**Comment by loongkc** [comment]
控制台
![image](https://github.com/imsyy/SPlayer/assets/103474466/6808680c-c6fd-4b09-bce5-adcc256bb391)

打开时有时候还会弹出这个，我是用的校园网，难道是这个原因？但是是有网络的啊，还是因为我电脑开了梯子？我关了梯子也还是加载不了评论
<img width="273" alt="Snipaste_2024-06-12_11-38-39" src="https://github.com/imsyy/SPlayer/assets/103474466/25ec3ea6-cdf1-4b1b-88a8-fa3f3263f2b7">
