### ISSUE TITLE
扫码登录使用深色模式时存在不能识别的问题

### ISSUE THREAD

**Issue by 80imike** [imsyy/SPlayer#181]
### 是网页端还是客户端

网页端

### 当前系统环境

 macos 14.5

### 当前 Node.js 及 npm 版本

 node:18-alpine

### 当前版本

dev 分支最新代码

### 具体信息

- 使用 mbp 14 寸 显示器
 
同一台机器上，扫码登录使用深色模式时，存在不能识别的问题，切换到浅色模式就可以正常识别

- 使用 21 寸 外接显示器

深色模式在同一台机器上，使用连接另一台 21 的显示器时也是可以识别的

可能是显示器分辨率问题引起的二维码变形引起的

---
再试了下 也有可能是网易云音乐客户端识别二维慢 ？？？

@imsyy 大佬有时间看看

**Comment by imsyy** [comment]
无法复现，目前已经对二维码做了处理，无论是否为深色模式都为白底，按理说不会无法扫描
