### ISSUE TITLE
无法下载歌曲，提示：账号会员等级不足，请提升权限。

### ISSUE THREAD

**Issue by khunt88** [imsyy/SPlayer#187]
### 是网页端还是客户端

网页端

### 当前系统环境

Ubuntu 22.04.4

### 当前 Node.js 及 npm 版本

无

### 当前版本

最新

### 具体信息

在公网ip下部署了docker，用自己的云音乐账号登录。开始可以下载几首，后面全都下载不了，提示：账号会员等级不足，请提升权限。
![微信图片_20240621131707](https://github.com/imsyy/SPlayer/assets/146688123/c9f1a8dc-0ad7-4314-a535-0a61db8ed06e)

**Comment by imsyy** [comment]
账号是会员吗

**Comment by khunt88** [comment]
> 账号是会员吗

不是云音乐会员呢，如果是的话我就在netease直接下载了。

**Comment by imsyy** [comment]
那无法提供下载功能，本软件不涉及该功能
