### ISSUE TITLE
安装失败，软件界面空白无内容

### ISSUE THREAD

**Issue by charyogo** [imsyy/SPlayer#188]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

V18.16.0 / v9.6.7

### 当前版本

2.0.9

### 具体信息

安装程序后首次打开提示如下问题，界面空白无内容
![1](https://github.com/imsyy/SPlayer/assets/119643143/9e934534-dee7-430b-9c7c-08fc0f86df68)

**Comment by imsyy** [comment]
#169
