### ISSUE TITLE
端口占用, 应用启动时异常, 程序界面无法加载

### ISSUE THREAD

**Issue by SlimeNull** [imsyy/SPlayer#210]
### 是网页端还是客户端

客户端

### 当前系统环境

Win11

### 当前 Node.js 及 npm 版本

v20.14.0 / 10.7.0

### 当前版本

v2.0.9

### 具体信息

保证 7899 端口被占用, 然后启动应用程序, 即报错.
大概是: Uncaught Exception: Error: listen  EADDRINUSE: address already in use 127.0.0.1: 7899

Clash Verge 使用了 7899 端口, SPlayer 在启动时应该检查端口是否已经被占用, 或者捕捉改异常, 并尝试使用其他端口.
尽管在 Release Note 中有提到端口占用时自动切端口, 但至少程序启动时这个端口占用会导致程序异常

**Comment by jcfun** [comment]
这个问题已经解决了，但是release里面没有更新，你可以拉代码自己打包一下
