### ISSUE TITLE
红心更新不及时

### ISSUE THREAD

**Issue by hexadecimal233** [imsyy/SPlayer#219]
### 是网页端还是客户端

客户端

### 当前系统环境

Windows 11

### 当前 Node.js 及 npm 版本

集成

### 当前版本

v2.0.9

### 具体信息

在Splayer外点的红心歌曲并不会显示已经红心，重启后正常显示

**Comment by imsyy** [comment]
不会实现该功能，这样会频繁请求网易云接口，且为非必要需求
