### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by Waynenet** [imsyy/SPlayer#22]
当列表中只有一首歌时。**播放完**后不能反复播放，也不能实现拖动进度条播放。

**Comment by imsyy** [comment]
已修复

**Comment by SiberiaBar2** [comment]
楼主想请教下，我在使用audio标签并利用ref调用play、pause方法时有时会遇到没有播放源这样的错误，请问你是怎么处理的？

**Comment by imsyy** [comment]
> 楼主想请教下，我在使用audio标签并利用ref调用play、pause方法时有时会遇到没有播放源这样的错误，请问你是怎么处理的？

估计是你audio标签的src地址过期了，可以在audio的error事件里重新获取播放地址并赋值给播放器就行了
