### ISSUE TITLE
请问首页加载不出来，一直跳网络连接错误怎么办

### ISSUE THREAD

**Issue by WhiteXBXB** [imsyy/SPlayer#229]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前 Node.js 及 npm 版本

无

### 当前版本

v2.0.9

### 具体信息

![屏幕截图 2024-08-04 213538](https://github.com/user-attachments/assets/99b2ffa6-d210-4882-bce3-909c7bee5b88)
![屏幕截图 2024-08-04 213634](https://github.com/user-attachments/assets/ad0923b7-c80e-41e9-a966-48fbc827e021)
火绒也关了，但是还是这样，网页版的本来加载不出来，后面可以了，谢谢

**Comment by zhangyang7** [comment]
mac版也一样，如何解决啊？

**Comment by Anotherzt** [comment]
同问，突然就这样了，提示网络连接错误，一直都好好的突然就不行了

**Comment by imsyy** [comment]
> mac版也一样，如何解决啊？

如果是刚发生的，那是因为网易云音乐今天下午崩了 🤣

**Comment by s3qazx** [comment]
一模一样，客户端 win11也是突然不行了
