### ISSUE TITLE
日文识别失败问题，导致无法切换歌曲，重复播放等问题。

### ISSUE THREAD

**Issue by OuOumm** [imsyy/SPlayer#232]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

最新release

### 当前版本

v2.0.9

### 具体信息

[1859064990](https://music.163.com/song?id=1859064990)

这首歌。
![image](https://github.com/user-attachments/assets/e09f304e-16cc-40fb-b93a-59acb04fc56d)

**Comment by imsyy** [comment]
测试了下，没问题啊

**Comment by OuOumm** [comment]
> 测试了下，没问题啊

今天试了下，能切了，可能是奇奇怪怪的问题
