### ISSUE TITLE
海外地區播放問題

### ISSUE THREAD

**Issue by NikolaJyun** [imsyy/SPlayer#238]
### 是网页端还是客户端

客戶端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v22.1.0/10.7.0

### 当前版本

v2.0.9

### 具体信息

请问台湾这边没使用加速器听不了
显示网络连接错误 有什么方法能解决吗?

![image](https://github.com/user-attachments/assets/86996921-d85e-4ffc-8046-1309e5a316e4)

**Comment by NikolaJyun** [comment]
@imsyy 再麻煩幫我看看有沒有解決方法 謝謝！

**Comment by NikolaJyun** [comment]
@imsyy 在麻煩幫我看看有沒有解決方法 謝謝！

**Comment by imsyy** [comment]
> @imsyy 在麻煩幫我看看有沒有解決方法 謝謝！

已嘗試使用 realIP 解決，可在 https://github.com/imsyy/SPlayer/actions/runs/10519432175 下載構建文件以安裝

![image](https://github.com/user-attachments/assets/8c5dfdcf-4fd7-49d1-89fe-f74caf9b59bb)

**Comment by NikolaJyun** [comment]
@imsyy 使用后可以正常播放收听 谢谢你这么快解决问题❤️

**Comment by imsyy** [comment]
> @imsyy 使用后可以正常播放收听 谢谢你这么快解决问题❤️ 然后希望歌词字体可以在更小 不太习惯看大字幕

好的，新版本是可以自定义的了
