### ISSUE TITLE
音量Bug

### ISSUE THREAD

**Issue by NikolaJyun** [imsyy/SPlayer#239]
### 是网页端还是客户端

客戶端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v22.1.0/10.7.0

### 当前版本

v2.10.0

### 具体信息

歌词模式下长按拖动音量
当歌词滚动到下一句
音量HUD会快速移动到左上角
然后导致调整音量失败

视频 //如果看不了跟我说下我再用它方式发
https://cdn.discordapp.com/attachments/469116283967766530/1276400422135005265/Desktop_2024.08.23_-_12.38.30.54.mp4?ex=66c96407&is=66c81287&hm=63ea54694aa7970678fee65a7e3d542d9018649838188899faf12bf43278d02b&

建议:
然后歌词模式下希望有一个按键可以点一下回到进入歌词模式前
虽然点击歌手或专辑也能跳出去但稍微有一点不直觉

**Comment by NikolaJyun** [comment]
@imsyy 开发大佬问一下 当初音量Bug是歌词模式下才会发生 当前的版本歌词模式没有音量条可以调整了 虽然也不影响使用就是了 后期会再添加回来吗!

當時BUG的影片
https://github.com/user-attachments/assets/de11f697-e970-446f-af96-5d0d4d8d81d3

當前版本歌詞模式截圖
![image](https://github.com/user-attachments/assets/0776af53-03f8-40b0-9a71-f368d44ac0dc)

**Comment by imsyy** [comment]
> @imsyy 开发大佬问一下 当初音量Bug是歌词模式下才会发生 当前的版本歌词模式没有音量条可以调整了 虽然也不影响使用就是了 后期会再添加回来吗!
> 
> 當時BUG的影片 https://github.com/user-attachments/assets/de11f697-e970-446f-af96-5d0d4d8d81d3
> 
> 當前版本歌詞模式截圖 ![image](https://private-user-images.githubusercontent.com/22559124/377452072-0776af53-03f8-40b0-9a71-f368d44ac0dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjExMjcsIm5iZiI6MTcyOTIyMDgyNywicGF0aCI6Ii8yMjU1OTEyNC8zNzc0NTIwNzItMDc3NmFmNTMtMDNmOC00MGIwLTlhNzEtZjM2OGQ0NGFjMGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAzMDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODg1NzQ4M2MyMzhmYzFiODllNzA4YzI2OGFmNTkzNzQ0YTc1NWIwNmRiMGE5MDIzNGJjNWJmYjFhNTU2NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TJudkuLudOGyix_fkhlgFLK_jGVqYRKTbCNIX9-Mob4)

会加的，就是忘记了 😂

**Comment by NikolaJyun** [comment]
@imsyy 好勒 不着急的 先把重要的项目搞搞 辛苦了！
