### ISSUE TITLE
vercel部署后报500错误

### ISSUE THREAD

**Issue by zhufacai** [imsyy/SPlayer#24]
资源加载不全，刷新就报服务器错误,我的站点music.joker.cc

**Comment by imsyy** [comment]
我的 api 做了跨域限制，你需要部署自己的网易云音乐 api

**Comment by imsyy** [comment]
> > > 我的 api 做了跨域限制，你需要部署自己的网易云音乐 api
> > 
> > 
> > 我就是自己部署的api，是不是用vercel域名不行，需要自定义域名吗？
> 
> 重新部署了api服务，替换了vercel域名，正常了。

OK
