### ISSUE TITLE
长时间暂停后无法正常继续播放

### ISSUE THREAD

**Issue by NikolaJyun** [imsyy/SPlayer#240]
### 是网页端还是客户端

客戶端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v22.1.0/10.7.0

### 当前版本

v2.10.0

### 具体信息

将SPlayer暂停闲置几个小时 重新点击播放 会出现未知网路错误 并跳到一下一首 无法接续原本的进度播放
![image](https://github.com/user-attachments/assets/55ca92d2-3b2d-469f-836d-49497a7231b9)

**Comment by NikolaJyun** [comment]
补充 跳到下一手后播放进度是前一首歌的时间轴开始播放

**Comment by NikolaJyun** [comment]
@imsyy 录制到了这个Bug了，当设备长时间不使用后，音乐播放会从原本暂停的时间点直接跳到下一首歌曲。老版本在这种情况下会显示网络错误（如截图所示），而最新的开发版则不会出现这个问题。

https://github.com/user-attachments/assets/5ac1be3c-0e7e-416a-80a4-dc09ac63425e

**Comment by imsyy** [comment]
> @imsyy 录制到了这个Bug了，当设备长时间不使用后，音乐播放会从原本暂停的时间点直接跳到下一首歌曲。老版本在这种情况下会显示网络错误（如截图所示），而最新的开发版则不会出现这个问题。
> 
> https://github.com/user-attachments/assets/5ac1be3c-0e7e-416a-80a4-dc09ac63425e
> 
> 

理论上是由于获取的网易播放源链接过期了，造成无法缓冲，触发播放错误，由于目前未对错误状态做出区分，从而导致默认下一曲（并且由于这种异常情况，导致进度未被重置），后面会尝试修复的

**Comment by NikolaJyun** [comment]
哈哈哈 太專業了 不在我的領域範圍 不過大致能理解你的意思 這個倒是不急 不怎麼影響使用體驗  重構忙完了再嘗試修復也不遲

**Comment by imsyy** [comment]
已解决该问题
