### ISSUE TITLE
登录方式真奇葩

### ISSUE THREAD

**Issue by yangtian997** [imsyy/SPlayer#242]
### 是网页端还是客户端

网页端

### 当前系统环境

手机

### 当前 Node.js 及 npm 版本

0000

### 当前版本

0.0.0

### 具体信息

如果手机端用，怎么登录？未注册的手机号登录还不行，显示登录出错，手机端就用不了了，你不可能一天到晚扛着电脑到处跑吧

**Comment by imsyy** [comment]
> ### 仅对移动端做了基础适配，不保证功能全部可用
>>请注意，本程序不打算开发移动端，也不会对移动端进行完美适配，仅保证基础可用性

看不见介绍中写的吗？
