### ISSUE TITLE
打开沉浸式播放时无法拖动移动窗口也打不开右键菜单

### ISSUE THREAD

**Issue by gdd00** [imsyy/SPlayer#246]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前 Node.js 及 npm 版本

v18.16 / v9.6.7

### 当前版本

2.0.9

### 具体信息

![sPlayer1](https://github.com/user-attachments/assets/1bf5fd39-c562-4486-a93c-a21a9aaaf765)
此时，此处无法直接左键拖动，也打不开右键菜单

**Comment by imsyy** [comment]
#174
