### ISSUE TITLE
显示渐变色背景时 8bit 屏幕产生了明显的色带

### ISSUE THREAD

**Issue by gdd00** [imsyy/SPlayer#247]
### 是网页端还是客户端

客户端

### 当前系统环境

win 10

### 当前 Node.js 及 npm 版本

v18.16 / v9.6.7

### 当前版本

2.0.9

### 具体信息

![sPlayer0](https://github.com/user-attachments/assets/4b618e7f-6af5-44a0-9699-3210ab2366d6)
沉浸式播放时 背景的渐变色  在 8bit 屏幕上会产生明显的色带

**Comment by FrzMtrsprt** [comment]
出现了，截屏看屏幕

**Comment by gdd00** [comment]
> 出现了，截屏看屏幕

搞错了，不是屏幕的问题。图像就是这样的。

**Comment by FrzMtrsprt** [comment]
截图被压缩后就是会产生一定程度的色调分离的，你可以在手机上打开splayer网页端看看播放页，就没有色调分离的情况了
