### ISSUE TITLE
登录二维码加载不出来

### ISSUE THREAD

**Issue by virtualvmw** [imsyy/SPlayer#250]
### 是网页端还是客户端

网页端

### 当前系统环境

docker

### 当前 Node.js 及 npm 版本

docker

### 当前版本

最新

### 具体信息

docker部署后加载不出来登录二维码

**Comment by imsyy** [comment]
请提供报错的网络请求详情

**Comment by virtualvmw** [comment]
不知道为什么，当我打开浏览器的开发者工具，刷新了下网页加载不出来的二维码出来了

**Comment by imsyy** [comment]
> 不知道为什么，当我打开浏览器的开发者工具，刷新了下网页加载不出来的二维码出来了

有条件还是建议使用客户端，网页端确实存在很多限制和问题
