### ISSUE TITLE
最新版托盘图标消失

### ISSUE THREAD

**Issue by thouser8** [imsyy/SPlayer#260]
### 是网页端还是客户端

客户端

### 当前系统环境

win11 24H2

### 当前 Node.js 及 npm 版本

使用提供的exe安装包进行安装

### 当前版本

v3.0.0-alpha.1

### 具体信息

![image](https://github.com/user-attachments/assets/20d30b18-ed47-4ac9-adcd-274de9fbcd09)
![image](https://github.com/user-attachments/assets/327050b4-3be0-451c-9929-fdea1dbaa19d)

**Comment by Starfallan** [comment]
win11 23h2 卸载后重新安装没有遇到相关问题，尝试重启下explorer？看下是哪边的问题

**Comment by thouser8** [comment]
> win11 23h2 卸载后重新安装没有遇到相关问题，尝试重启下explorer？看下是哪边的问题

不起作用，以及电脑重启、软件重置和重装也依旧，便携版和安装版也分别都试了

**Comment by lijingbonb** [comment]
我也是
win11 24h2
npm 9.8.1
nodejs v18.18.1
打包的客户端版本：v3.0.0-alpha.1
![Clip_2024-09-26_21-25-33](https://github.com/user-attachments/assets/cb0e7755-5a3d-413c-91f5-6ca20829eadd)

**Comment by imsyy** [comment]
https://github.com/imsyy/SPlayer/commit/62c9dc33db789955b83232e15d3d34e7fdd9f58b
该提交进行了错误的注释，造成了图标路径错误，稍后会修复

**Comment by thouser8** [comment]
> [62c9dc3](https://github.com/imsyy/SPlayer/commit/62c9dc33db789955b83232e15d3d34e7fdd9f58b) 该提交进行了错误的注释，造成了图标路径错误，稍后会修复

了解了，辛苦开发者
