### ISSUE TITLE
桌面歌词在拖拽到右下角放置并且锁住后，后续点击歌词没反应，无法解锁，歌词移动不了

### ISSUE THREAD

**Issue by monkey-papa** [imsyy/SPlayer#261]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

node：18.17.0 ；npm：9.6.7

### 当前版本

v2.0.9

### 具体信息

初次运行本地项目，自动打开桌面应用，播放一首歌曲，选择打开歌词，歌词默认出现在了左上角顶部，并不是我想要展示歌词的位置，所以我进行移动歌词移动到右下角并且锁住，然后想解锁就点击歌词没任何反应

**Comment by imsyy** [comment]
目前可在托盘菜单中解锁
