### ISSUE TITLE
搜索栏交互失败

### ISSUE THREAD

**Issue by NikolaJyun** [imsyy/SPlayer#262]
### 是网页端还是客户端

客戶端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

N/A

### 当前版本

v3.0.0-alpha.2

### 具体信息

知道是Alpha版不清楚imsyy是不是已经知道有该BUG还是提出来回报一下!

搜索栏交互失败
搜索栏中的单曲、歌手交互失败
直接搜索、专辑交互正常

**Comment by NikolaJyun** [comment]
https://github.com/user-attachments/assets/af5136e1-2407-4966-a69d-1e6967e965cf

**Comment by imsyy** [comment]
这个还没加 ~~其实是忘记了~~，还有部分页面的收藏和点赞什么的也都还没加上

**Comment by NikolaJyun** [comment]
好的 慢慢來 辛苦了!

**Comment by imsyy** [comment]
已修复

**Comment by NikolaJyun** [comment]
@imsyy 感謝 辛苦了!
