### ISSUE TITLE
CTRL+方向键切歌设置反了

### ISSUE THREAD

**Issue by yanjie233** [imsyy/SPlayer#264]
### 是网页端还是客户端

客户端

### 当前系统环境

Win11

### 当前 Node.js 及 npm 版本

客户端

### 当前版本

V.3.0.0-alpha.2

### 具体信息

在最新的V3.0.0-alpha.2版本中，按住Ctrl键和方向键切歌时按住→（右）将会切换为上一首，按住←（左）将会跳转到下一首，设置反了吧，按道理应该为右为下一首，左为上一首吧。
感谢开发者辛勤的付出，有空可以排查一下！

**Comment by imsyy** [comment]
已更正
