### ISSUE TITLE
请求错误状态码404

### ISSUE THREAD

**Issue by nlxxtw** [imsyy/SPlayer#266]
### 是网页端还是客户端

网页版

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

verce部署

### 当前版本

v3.0.0-alpha2

### 具体信息

![image](https://github.com/user-attachments/assets/98e39b05-028b-4334-83fe-b493a221a4be)

**Comment by nlxxtw** [comment]
![image](https://github.com/user-attachments/assets/0ca1ae0c-623a-4cb7-8489-3986fe0e10ae)
这是客户端手机号登入提示错误

**Comment by imsyy** [comment]
应该是 api 地址没填好
国庆了，开摆，假后再说 👻

**Comment by Xuan-Xuann** [comment]
请不要使用第三方客户端，收紧了，现在让你改密码，下次直接冻结账号，第三方客户端无一幸免。最近尽量避免使用第三方客户端。同时也建议开发者能提醒使用者，避免导致封号
