### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by sunshineluo** [imsyy/SPlayer#27]
部署到vercel上时提示服务器错误，但是env文件的在线API地址我是填写了的，但还是没用，求解

**Comment by imsyy** [comment]
试试将 api 中的 `server.js` 文件中的响应头改成你的线上项目地址试试

**Comment by sunshineluo** [comment]
> 
API的文件夹里面好像没有server.js这个文件啊

**Comment by imsyy** [comment]
😂 是网易云 API 的文件 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/0ff32acdc13e7c163abfe7e406bbaf912b2f24d9/server.js#L146

**Comment by imsyy** [comment]
或者是网易云 API 的接口做了域名缓存机制，你可以等一段时间再试试是否正常

**Comment by sunshineluo** [comment]
我这个接口都是别人部署，我只是拿来用的，自己没部署，所以就不知道为啥了，另外，我发现移动端网页歌词显示有点不太流畅，感觉有点卡卡的

**Comment by imsyy** [comment]
> 我这个接口都是别人部署，我只是拿来用的，自己没部署，所以就不知道为啥了，另外，我发现移动端网页歌词显示有点不太流畅，感觉有点卡卡的

是的，逐字歌词和滚动这一块还在优化中

**Comment by Xuan-Xuann** [comment]
您好 我也遇到了此问题 但是我已经按照文档要求  部署了本地API   在env文件中添加了接口地址 但是依旧不起作用
![image](https://github.com/imsyy/SPlayer/assets/98678327/51a94555-4b75-4320-88c8-0523b2b2df75)
![image](https://github.com/imsyy/SPlayer/assets/98678327/c59deb8d-2992-4426-af0f-ab524543b1bc)
![image](https://github.com/imsyy/SPlayer/assets/98678327/7b39ac9d-3298-49a6-a615-9d558aab4971)
