### ISSUE TITLE
近期请勿在第三方客户端中登录账号，否则将会导致封号

### ISSUE THREAD

**Issue by imsyy** [imsyy/SPlayer#270]
请不要使用第三方客户端，收紧了，现在让你改密码，下次直接冻结账号，第三方客户端无一幸免。最近尽量避免使用第三方客户端。同时也建议开发者能提醒使用者，避免导致封号

_最初由 Xuan-Xuann 在 https://github.com/imsyy/SPlayer/issues/266#issuecomment-2393187454 发布_

**Comment by jcfun** [comment]
#270 解决了登录风控问题？

**Comment by jcfun** [comment]
NeteaseCloudMusicApi 4.23.0 解决了登录风控问题？

**Comment by imsyy** [comment]
> NeteaseCloudMusicApi 4.23.0 解决了登录风控问题？

还不清楚，建议近期先不要使用登录功能

**Comment by NikolaJyun** [comment]
@imsyy 原本就有登入的需要登出嗎 因為剛剛更新完打開啥事也沒有 前兩天也有開起來聽音樂 那時候還是2.0.0.alpha2

**Comment by imsyy** [comment]
> @imsyy 原本就有登入的需要登出嗎 因為剛剛更新完打開啥事也沒有 前兩天也有開起來聽音樂 那時候還是2.0.0.alpha2

还处于登录状态的应该可以继续使用，我的也处于登录状态，目前并没有被封号，不过记得在设置中关闭 `听歌打卡` 功能，据传可能这个也会导致账号异常

**Comment by NikolaJyun** [comment]
@imsyy 感謝解答 因為聽歌打卡預設就關閉 所以目前沒有問題!

**Comment by Xuan-Xuann** [comment]
> @imsyy 感謝解答 因為聽歌打卡預設就關閉 所以目前沒有問題!

您好，现在目前是用网页端接口，都会被检测，貌似到目前为止没能解决这个问题。即使关闭听歌打卡，也同样收到了账号封禁的消息。我建议是如果是自己主账号，最好不要使用第三方客户端，可以准备着手考虑换其他平台了

**Comment by NikolaJyun** [comment]
> > @imsyy 感謝解答 因為聽歌打卡預設就關閉 所以目前沒有問題!
> 
> 您好，现在目前是用网页端接口，都会被检测，貌似到目前为止没能解决这个问题。即使关闭听歌打卡，也同样收到了账号封禁的消息。我建议是如果是自己主账号，最好不要使用第三方客户端，可以准备着手考虑换其他平台了

我是用程序的版本没遇到这问题今天更新Alpha.3的版本也听了一天啥事都没有 先给开发 @imsyy 一点时间看有没有办法解决吧还是不要冒着风险登入况且不登入也能听应该也没太大的问题

**Comment by wcshen** [comment]
ref: https://github.com/HyPlayer/HyPlayer/releases/tag/2.1.37.5872

**Comment by s-yh-china** [comment]
目前是否有更多关于账号封禁情况的消息?

**Comment by Xuan-Xuann** [comment]
> 目前是否有更多关于账号封禁情况的消息?
请不要使用，前天我账号也被封掉了，不是用网页接口是pc接口

**Comment by jcfun** [comment]
> > 目前是否有更多关于账号封禁情况的消息?
> > 请不要使用，前天我账号也被封掉了，不是用网页接口是pc接口

你之前用过其它登录方式吗？我使用uid登录一个多星期也没有被封

**Comment by imsyy** [comment]
> > > 目前是否有更多关于账号封禁情况的消息?
> > > 请不要使用，前天我账号也被封掉了，不是用网页接口是pc接口
> 
> 你之前用过其它登录方式吗？我使用uid登录一个多星期也没有被封

UID 登录是肯定不会被封的，全程没有用到任何用户信息

**Comment by ssxwcz** [comment]
直接用cookie登录一周多暂时也没被封。

**Comment by ExoticSkywing** [comment]
所以现在到底是啥情况？能登陆吗？

**Comment by imsyy** [comment]
> 所以现在到底是啥情况？能登陆吗？

目前仅推荐使用 UID 方式登录使用

**Comment by ExoticSkywing** [comment]
谢谢，弱弱问下 uid 方式咋登录😂

**Comment by imsyy** [comment]
> 谢谢，弱弱问下 uid 方式咋登录😂

目前仅支持客户端，在切换登录方式的下方，里面有说明

**Comment by ExoticSkywing** [comment]
好吧，没用过客户端，只用了 web 版

**Comment by imsyy** [comment]
> 好吧，没用过客户端，只用了 web 版

在最新版 Web 端也是支持的，但是基本不可用
