### ISSUE TITLE
海外手机号无法登录

### ISSUE THREAD

**Issue by FrzMtrsprt** [imsyy/SPlayer#273]
### 是网页端还是客户端

客户端

### 当前系统环境

Windows 11 24H2

### 当前 Node.js 及 npm 版本

打包版本

### 当前版本

3.0.0-alpha.4（开发版 2e0f448）

### 具体信息

1. 打开登录窗口，选择验证码登录
2. 将国家切换至非中国的任意地区
3. 输入当地的合法手机号，出现错误提示“请输入正确的手机号”
4. 尝试点击获取验证码，无反应

当国家选择非中国时，不应校验手机号格式。

**Comment by imsyy** [comment]
已修复
