### ISSUE TITLE
未登录时，无法获取动态封面

### ISSUE THREAD

**Issue by FrzMtrsprt** [imsyy/SPlayer#274]
### 是网页端还是客户端

客户端

### 当前系统环境

Windows 11 24H2

### 当前 Node.js 及 npm 版本

打包版本

### 当前版本

3.0.0-alpha.4（开发版 2e0f448）

### 具体信息

1. 在设置中打开动态封面
2. 退出登录
3. 播放任意歌曲并打开播放界面，右上角报错“请求错误，状态码: 301”
4. 登录账号
5. 播放任意歌曲并打开播放界面，右上角无报错
6. 直接访问https://docs-neteasecloudmusicapi.vercel.app/song/dynamic/cover?id=18520488 ，可以看到response中有“需要登录”

![image](https://github.com/user-attachments/assets/14a9aed0-7111-4f75-83ee-41f5aededdb6)

```json
{
  "code": 301,
  "message": "系统错误",
  "debugInfo": null,
  "data": null,
  "failData": null,
  "msg": "需要登录"
}
```

**Comment by imsyy** [comment]
已修复

**Comment by FrzMtrsprt** [comment]
UID登录模式下仍会报错

https://github.com/imsyy/SPlayer/blob/a8f01d5728fcc241d499cb81745d2b7ddb504307/src/components/Player/PlayerCover.vue#L62

这里应为`isLogin() != 1`

**Comment by imsyy** [comment]
讲道理，我觉得这个动态封面效果很差

**Comment by FrzMtrsprt** [comment]
感觉做成Spotify那样一直循环播放的会好一点，如果开头结尾不连续可以渐变过渡过去
