### ISSUE TITLE
一些无关紧要的小问题

### ISSUE THREAD

**Issue by FrzMtrsprt** [imsyy/SPlayer#275]
### 是网页端还是客户端

客户端

### 当前系统环境

WIndows 11

### 当前 Node.js 及 npm 版本

打包版本

### 当前版本

3.0.0-beta.1

### 具体信息

1. 打开任意专辑页面，第一位艺术家重复，且无法点击
2. 较长歌单的歌曲总数不准确
![{D8CD4839-9B6A-4A9C-9140-BA2F39B426C6}](https://github.com/user-attachments/assets/d5086fcc-11d0-4576-bfec-806383455753)
3. 播放艺术家全部歌曲时，只有前100首被加入播放列表，向下滚动后才会加入更多歌曲
4. 在设置中关闭歌词翻译和注音后，播放页和播放栏的歌词仍然带有翻译（和注音）
5. 本地歌曲页面中，文件元数据的“备注”项会把列宽拉到超长
![{1CE8A2FA-DC8E-4530-83D8-7C0E79E87C9D}](https://github.com/user-attachments/assets/84233206-0060-4e97-912c-dba7d477ea1e)
6. 可以更新neteasecloudmusicapi到4.23.3？
7. 待补充

**Comment by akFace** [comment]
锁定桌面歌词后怎么解锁，找不到开关

**Comment by imsyy** [comment]
> 锁定桌面歌词后怎么解锁，找不到开关

在托盘的右键菜单中

**Comment by akFace** [comment]
> > 锁定桌面歌词后怎么解锁，找不到开关
> 
> 在托盘的右键菜单中

隐藏太深了，应该在设置或者鼠标移到歌词上显示解锁图标就行，还有就是可以不用显示歌名和作者的

**Comment by imsyy** [comment]
> > > 锁定桌面歌词后怎么解锁，找不到开关
> > 
> > 
> > 在托盘的右键菜单中
> 
> 隐藏太深了，应该在设置或者鼠标移到歌词上显示解锁图标就行，还有就是可以不用显示歌名和作者的

桌面歌词近期不会做出调整，可提交 pr

**Comment by jcfun** [comment]
> > > > 锁定桌面歌词后怎么解锁，找不到开关
> > > 
> > > 
> > > 在托盘的右键菜单中
> > 
> > 
> > 隐藏太深了，应该在设置或者鼠标移到歌词上显示解锁图标就行，还有就是可以不用显示歌名和作者的
> 
> 桌面歌词近期不会做出调整，可提交 pr

桌面歌词在播放音乐时并手动移动后会自己变大，而且会漂移一段时间，不知道你发现没有。我尝试定位问题，但是没有找到问题在哪里
