### ISSUE TITLE
docker版网页上部分音乐无法播放

### ISSUE THREAD

**Issue by hubeiyaowenping** [imsyy/SPlayer#281]
### 是网页端还是客户端

网页

### 当前系统环境

docker

### 当前 Node.js 及 npm 版本

v18

### 当前版本

v3.0.0-alpha.4

### 具体信息

docker版网页上部分音乐无法播放，win版却可以播放

**Comment by s12mmm3** [comment]
所以是什么歌曲不能放

**Comment by hubeiyaowenping** [comment]
所有带vip标识的都不能播放
