### ISSUE TITLE
歌词错位

### ISSUE THREAD

**Issue by kazukokawagawa** [imsyy/SPlayer#283]
### 是网页端还是客户端

web

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

docker

### 当前版本

v3.0.0a4

### 具体信息

复原过程
![image](https://github.com/user-attachments/assets/cc3c26e2-b1f2-4eef-9be1-8cd40ed0155e)
在这句话的时候暂停
然后点击右上角把歌词界面关闭
再点击左下角封面开回来
![image](https://github.com/user-attachments/assets/2a11f993-dd28-4630-b50e-5f1142fc2125)
错误复原，这是我的设置
![image](https://github.com/user-attachments/assets/7b49e674-e609-443e-bce0-66cbf7898154)
![image](https://github.com/user-attachments/assets/f96525b2-c7ed-4902-9f23-59d5e1ed96e0)
![image](https://github.com/user-attachments/assets/5c028b53-18e6-4943-83ab-2044587c1cf8)
![image](https://github.com/user-attachments/assets/4f6c1804-2fb3-47a6-9ef1-a9c20a934b42)
![image](https://github.com/user-attachments/assets/ec5249ec-efbd-47bc-b107-1263560e6eb2)
![image](https://github.com/user-attachments/assets/b581df93-6ae2-4efa-b70d-817873a9f7c2)
![image](https://github.com/user-attachments/assets/6128fdbd-e302-445c-8191-a33d1976365a)

**Comment by imsyy** [comment]
AMLL 组件问题，可关闭或者开启全屏播放器留存
