### ISSUE TITLE
The 'screen' module can't be used for app ready event

### ISSUE THREAD

**Issue by NimbleWing** [imsyy/SPlayer#289]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前 Node.js 及 npm 版本

v20.18.0/pnpm v9.12.2

### 当前版本

dev

### 具体信息

本地pnpm run dev 运行后报[The 'screen' module can't be used for app ready event]错误，
![image](https://github.com/user-attachments/assets/127d0ae0-07f1-4680-a11b-1599717fb568) 问题应该出在这里

**Comment by imsyy** [comment]
https://github.com/imsyy/SPlayer/commit/eb39b85a8b968bfe98286ce90c56ed92cf8e1dd1 已修复
