### ISSUE TITLE
ubuntu24.04上snap版本desktop报缺少exec字段

### ISSUE THREAD

**Issue by Joker2770** [imsyy/SPlayer#299]
### 是网页端还是客户端

客户端

### 当前系统环境

ubuntu24.04

### 当前 Node.js 及 npm 版本

未知（snap安装）

### 当前版本

3.0.0-beta.1

### 具体信息

ubuntu24.04上`snap install splayer`安装后，双击桌面splayer图标启动过程报错（desktop报缺少exec字段），程序无法启动，在终端通过命令`splayer`可以启动。

**Comment by imsyy** [comment]
已修复，可切换至 beta 通道安装
