### ISSUE TITLE
点击周杰伦的全部歌曲会跳到李荣浩的

### ISSUE THREAD

**Issue by losie** [imsyy/SPlayer#30]
https://music.imsyy.top/artist/songs?id=6452&page=1
![image](https://user-images.githubusercontent.com/36534236/235902150-c16d8bf4-dfde-4eae-88ac-5d795c7cd145.png)

**Comment by losie** [comment]
![image](https://user-images.githubusercontent.com/36534236/235902838-2f386dda-e145-4cc7-99b6-48578c07f5bf.png)
好像播放不了

**Comment by imsyy** [comment]
> ![image](https://user-images.githubusercontent.com/36534236/235903005-dba2dba4-1e79-4d12-8fdf-69fdb6d26516.png)
> 
> 好像播放不了

是的，周杰伦的歌解灰需要酷我音源，但是酷我音源不支持 `https`，所以无法在生产环境中使用
