### ISSUE TITLE
win10客户端使用验证码方式登录不进去

### ISSUE THREAD

**Issue by gengjile** [imsyy/SPlayer#304]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前 Node.js 及 npm 版本

v9.6.7

### 当前版本

v2.0.9

### 登录不进去
我在win10电脑端使用验证码登录方式尝试登录，输入验证码之后，显示登录失败。
多次尝试都是如此。
(Node.js没找到多少版本的，随便写的）

**Comment by imsyy** [comment]
不要使用这个方式登录了
