### ISSUE TITLE
通过关闭按钮最小化时，无法打开主界面；

### ISSUE THREAD

**Issue by lhstock** [imsyy/SPlayer#308]
### 是网页端还是客户端

客户端

### 当前系统环境

macOS (intel)

### 当前 Node.js 及 npm 版本

v18.19.1/v10.2.4

### 当前版本

3.0.0-alpha.4

### 具体信息

如题，点击关闭后，首次弹窗二次确认时，选择最小化，并不再提示就会出现此情况，暂时也没发现可以修改恢复二次确认的设置；

**Comment by imsyy** [comment]
![image](https://github.com/user-attachments/assets/b4051bad-da2b-478c-aabc-e4a8ddac92dc)

可以先开启该选项
