### ISSUE TITLE
v3.0.0-alpha.4不能加载本地歌曲

### ISSUE THREAD

**Issue by liubo637** [imsyy/SPlayer#309]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

x

### 当前版本

v3.0.0-alpha.4

### 具体信息

v3.0.0-alpha.4版本不能扫描出本地歌曲

**Comment by imsyy** [comment]
检查下目录配置吧

**Comment by liubo637** [comment]
目录配置是没问题的，2版也正常，就3版找不到歌曲。
![QQ20241220-182604](https://github.com/user-attachments/assets/ccfa75f6-1db7-4d42-982b-21dfb1cdc836)
![QQ20241220-182545](https://github.com/user-attachments/assets/e7aec879-8cf7-4dd6-8a18-76dbc30e2f6f)
