### ISSUE TITLE
一些BUG反馈

### ISSUE THREAD

**Issue by Akimio521** [imsyy/SPlayer#31]
1. 移动端只有「首页」没有「发现」和「我的」这两个页面
2. iOS端用Safari进入网页播放音乐无法获取专辑封面和暂停，但是可以上一首/下一首音乐
3. 移动端播放器没有上下首的按钮，只能播放和暂停
4. 歌词页面状态栏取色有问题
5. 希望移动端歌曲页面新增上下首音乐和暂停播放键，而不是已进入就是歌词页（参考AppleMusic）
6. 希望大佬的项目越做越好

**Comment by imsyy** [comment]
感谢建议，会改进的 🎉

**Comment by zui-lang** [comment]
突然发现歌单居然没有播放键，只能通过点击歌曲播放，喜欢能把播放键，随机播放什么的加上，感谢大佬

**Comment by zui-lang** [comment]
日语歌默认会带罗马音，而且关掉翻译罗马音依然在，不知道这个能不能像为每种显示做单独的开关

**Comment by zui-lang** [comment]
移动端好像没办法把歌曲添加到歌单中

**Comment by imsyy** [comment]
> 日语歌默认会带罗马音，而且关掉翻译罗马音依然在，不知道这个能不能像为每种显示做单独的开关

这个在播放器设置中关闭 `歌词音译` 就行了

![image](https://user-images.githubusercontent.com/42232682/236362947-c51f17bd-5abb-4831-beab-5829138061a7.png)

**Comment by imsyy** [comment]
> 突然发现歌单居然没有播放键，只能通过点击歌曲播放，喜欢能把播放键，随机播放什么的加上，感谢大佬

这个稍后会加上的

**Comment by WWWALINTOP** [comment]
云盘上传音乐异常，别人同样的能上传，我的就不行

**Comment by WWWALINTOP** [comment]
用了腾讯云部署的API网站打开很快，但是登录不来账户
