### ISSUE TITLE
Mac用户端无法播放本地音乐

### ISSUE THREAD

**Issue by ryanwuson** [imsyy/SPlayer#316]
### 是网页端还是客户端

客户端

### 当前系统环境

macOS Sequoia 15.1.1

### 当前 Node.js 及 npm 版本

无

### 当前版本

3.0.0-beta.1

### 具体信息

Mac用户端无法播放本地音乐，会一直出现「当前重试次数过多，请稍后再试」。

https://github.com/user-attachments/assets/fb6207d2-8363-4efa-9096-c246da4edeb6

**Comment by imsyy** [comment]
#315

**Comment by Icy-Mountain-studio** [comment]
是的是的！我Linux端也有相同的问题！！！！
