### ISSUE TITLE
构建完成后打开完成请求错误

### ISSUE THREAD

**Issue by KKISO574** [imsyy/SPlayer#32]
配置了.env里面的api，但是打开主页后没有其他的封面和歌单，只有一个导航栏，显示请求错误，不知道是不是哪里没有配置。

**Comment by imsyy** [comment]
应该是跨域了，控制台有报错吗？

**Comment by KKISO574** [comment]
上证书就可以了，https的问题，已解决

**Comment by imsyy** [comment]
好的

**Comment by KKISO574** [comment]
但是解灰失败不知道是什么原因，接口我自己也搭建了，就是用的你那个unm的，不知道什么情况

**Comment by imsyy** [comment]
目前网页端只有部分歌曲能支持，因为解灰的酷我音源不支持 `https` 访问，所以无法在生产环境中使用，开发环境下是正常的，目前还没想到什么好办法
