### ISSUE TITLE
splayer 3.0.0 beta-1版本无法扫描本地歌曲（flac格式）

### ISSUE THREAD

**Issue by xiao497** [imsyy/SPlayer#321]
### 是网页端还是客户端

客户端

### 当前系统环境

Windows11 22H2

### 当前 Node.js 及 npm 版本

v18.16

### 当前版本

3.0.0 beta-1

### 具体信息

此前用的都是splayer 2.06版本，可以正常识别所有音乐，但是今天更新了splayer 3.0.0 beta -1后所有歌曲无法识别

**Comment by imsyy** [comment]
#315
