### ISSUE TITLE
ios标签页和桌面图标bug

### ISSUE THREAD

**Issue by zui-lang** [imsyy/SPlayer#38]
也不算bug吧，就是没适配，样式不太好看
![image](https://github.com/imsyy/SPlayer/assets/77880495/6b905370-a52b-46a8-882e-3dd2d200b055)
可以参考一下这篇[文章](https://blog.zhheo.com/p/5728da61.html)

**Comment by imsyy** [comment]
收到

**Comment by imsyy** [comment]
已修复
