### ISSUE TITLE
歌词显示问题

### ISSUE THREAD

**Issue by blogclub** [imsyy/SPlayer#40]
![截屏2023-05-22 17 31 05](https://github.com/imsyy/SPlayer/assets/72648772/2525f05b-f062-4f15-8a15-c54c4f73224f)
Mac端safari浏览器-逐字歌词 字的周围有黄色细边框，望修复，谢谢

**Comment by imsyy** [comment]
目前已经有所改善，等后面我再改变下逐字歌词逻辑吧
