### ISSUE TITLE
下载音乐一直转圈

### ISSUE THREAD

**Issue by PhathomBR** [imsyy/SPlayer#43]
选完音质后点下载一直转圈没反应

**Comment by imsyy** [comment]
所有都是吗，还是具体的哪一首

**Comment by PhathomBR** [comment]
> 所有都是吗，还是具体的哪一首

试了下，所有都是，点了显示正在下载但是一直转圈，chrome的下载里没反应

**Comment by imsyy** [comment]
> > 所有都是吗，还是具体的哪一首
> 
> 试了下，所有都是，点了显示正在下载但是一直转圈，chrome的下载里没反应

是演示站点吗，还是自己部署的？我这边 Edge 测试正常，可以看看控制台有报错吗

**Comment by imsyy** [comment]
已修复
