### ISSUE TITLE
使用UNM-SERVER解锁的一些问题和我个人解决方案

### ISSUE THREAD

**Issue by beer-on-ice** [imsyy/SPlayer#45]
目前使用UNM-SERVER解锁后，如果以QQ音乐优先，匹配以后会报错500，提示匹配失败，
![image](https://github.com/imsyy/SPlayer/assets/25942344/0a958d22-d077-4636-a1fa-9c2d5f97f1d6)
这里我的方案是kuwo音源优先。此时能拿到kuwo音源的歌曲，不过由于是http协议，访问资源会报错403，
这里我的方案是部署此反代项目 https://github.com/beer-on-ice/vercel_reverse_proxy，成功后得到一个反代的域名如 http://xxx.vercel.app
![image](https://github.com/imsyy/SPlayer/assets/25942344/07f7a84e-b571-428a-89e1-73541bebc352)

然后在SPlayer vercel项目变量中添加 VITE_PROXY_API = https://xxx.vercel.app/proxy/
![image](https://github.com/imsyy/SPlayer/assets/25942344/771150b2-d421-49d9-9a60-8c4f23bcf08b)

最后将src/components/Player/index.vue中第367行替换为
`player.value = createSound(res.data.url.replace(/\?bitrate/, '').replace(/http:\/\//, import.meta.env.VITE_PROXY_API));` 
![image](https://github.com/imsyy/SPlayer/assets/25942344/897f81b4-c9d2-4693-92a8-8e53934d6d26)

不过目前每次随作者更新代码后，再改动比较繁琐，希望作者能修复下，感谢作者项目

**Comment by imsyy** [comment]
感谢大佬，我去试试

**Comment by beer-on-ice** [comment]
[https://github.com/beer-on-ice/vercel_reverse_proxy](https://github.com/beer-on-ice/vercel_reverse_proxy%EF%BC%8C%E6%88%90%E5%8A%9F%E5%90%8E%E5%BE%97%E5%88%B0%E4%B8%80%E4%B8%AA%E5%8F%8D%E4%BB%A3%E7%9A%84%E5%9F%9F%E5%90%8D%E5%A6%82) 这个反代还是不稳，改用了cloudflare worker部署的反代，周董的歌基本都能匹配播放 https://github.com/beer-on-ice/cfworker_reverse_proxy

**Comment by beer-on-ice** [comment]
[https://github.com/beer-on-ice/vercel_reverse_proxy](https://github.com/beer-on-ice/vercel_reverse_proxy%EF%BC%8C%E6%88%90%E5%8A%9F%E5%90%8E%E5%BE%97%E5%88%B0%E4%B8%80%E4%B8%AA%E5%8F%8D%E4%BB%A3%E7%9A%84%E5%9F%9F%E5%90%8D%E5%A6%82)这个反代还是不太稳，有些歌还是403，改用部署在cloudflare worker的反代，目前周董的都能正确播放 [https://github.com/beer-on-ice/cfworker_reverse_proxy](https://github.com/beer-on-ice/cfworker_reverse_proxy)

**Comment by imsyy** [comment]
> [https://github.com/beer-on-ice/vercel_reverse_proxy](https://github.com/beer-on-ice/vercel_reverse_proxy%EF%BC%8C%E6%88%90%E5%8A%9F%E5%90%8E%E5%BE%97%E5%88%B0%E4%B8%80%E4%B8%AA%E5%8F%8D%E4%BB%A3%E7%9A%84%E5%9F%9F%E5%90%8D%E5%A6%82)这个反代还是不太稳，有些歌还是403，改用部署在cloudflare worker的反代https://github.com/beer-on-ice/cfworker_reverse_proxy ，目前周董的歌都能正确播放 ， 在SPlayer vercel项目变量中添加 VITE_PROXY_API = https://xxx.xxx.xxx/http/
> 
> ![image](https://user-images.githubusercontent.com/25942344/242141902-30f634b8-4c49-4f6b-8612-0fecdec7748a.png)

ok，我去试试

**Comment by imsyy** [comment]
我目前对 `src\components\Player\index.vue` 做了一下兼容，由于感觉还是在 `UNM-SERVER` 处做一下反代处理比较好，所以你需要更新一下 `UNM-SERVER`，把反代地址填到 `env` 环境变量就行

**Comment by beer-on-ice** [comment]
好的，感谢
