### ISSUE TITLE
PWA应用图标问题

### ISSUE THREAD

**Issue by Akimio521** [imsyy/SPlayer#46]
网站图标已经更改，但是pwa应用图标依旧是透明图标

**Comment by imsyy** [comment]
忘记修改图片了 😂

**Comment by imsyy** [comment]
改了其中一个图片，试试咋样，由于我这也没有苹果设备，所以不好判断

**Comment by zui-lang** [comment]
> 改了其中一个图片，试试咋样，由于我这也没有苹果设备，所以不好判断

music.imsyy.top吗，我看pwa样式还是没有变化，Windows11下也没变化

**Comment by zui-lang** [comment]
应该要改pwa的图标哦，我之前发的文章是对没有适配pwa应用的网页进行的修改

iOS端的应用权重应该是
pwa应用 > Safari适配 > 默认

**Comment by zui-lang** [comment]
> 应该要改pwa的图标哦，我之前发的文章是对没有适配pwa应用的网页进行的修改
> 
> iOS端的应用权重应该是
> pwa应用 > Safari适配 > 默认

这个权重是我的经验，不一定准确

**Comment by imsyy** [comment]
可以试下新版 @Akimio521
