### ISSUE TITLE
歌单添加歌曲BUG

### ISSUE THREAD

**Issue by Akimio521** [imsyy/SPlayer#48]
举个例子描述一下问题：
假设歌单A中有40首歌，且其中没有歌曲a，向歌单A其中添加歌曲a，此时歌单A中显示有41首歌曲且有歌曲a，无BUG，但是只要再次像歌单A中添加歌曲a，这时会弹窗显示添加成功，且歌单A中有42首歌，但用官方的app查看只有41首歌，且只有第一次添加的歌曲a

建议在添加歌曲时查看歌单是否已经添加该歌曲，并给出是否重复添加的选项

**Comment by imsyy** [comment]
问题是要是在每次点击前都遍历一次歌单的所有歌曲来检查是否重复的话，如果这个歌单的歌曲数量太多，那样可能会很慢 😢

**Comment by zui-lang** [comment]
> 问题是要是在每次点击前都遍历一次歌单的所有歌曲来检查是否重复的话，如果这个歌单的歌曲数量太多，那样可能会很慢 😢

那官方APP是怎么实现的呢😂

**Comment by imsyy** [comment]
谁知道呢，估计官方就是这样实现的吧，但是这边的接口只能按照这样：请求对应歌单信息拿到歌曲总数 -> 用歌曲总数请求全部歌曲信息（如果歌单里有几百首的话这一步会很慢） -> 判断将要添加的歌曲是否在该歌单的全部歌曲中

**Comment by imsyy** [comment]
问题在于官方在添加到歌单的这个接口中只会返回 true，即使存在也是返回 true 😂

**Comment by zui-lang** [comment]
官方接口确实是一个问题。那能不能先判断歌单数量，如果数量小于50首就进行匹配，超过50首就直接添加？

**Comment by imsyy** [comment]
确实可行

**Comment by zui-lang** [comment]
感觉可以出一个流畅模式，对匹配歌单数量和歌词页面渲染精细度进行调整

**Comment by imsyy** [comment]
> 感觉可以出一个流畅模式，对匹配歌单数量和歌词页面渲染精细度进行调整

这可是个大工程了 🤣，等大版本的时候我看能不能搞定

**Comment by zui-lang** [comment]
不着急，慢慢来
