### ISSUE TITLE
夜间模式识别问题

### ISSUE THREAD

**Issue by zui-lang** [imsyy/SPlayer#49]
这个算不上BUG，但感觉有点影响体验，先打开深色模式再进入，此时pwa应用还是浅色模式，需要先关闭深色模式再打开应用才能切换到深色模式

建议在打开应用时先检测一次系统模式

浏览器：Safari
系统： IOS16.1.2

**Comment by imsyy** [comment]
目前只要开启了跟随系统，在打开应用时就会先检测一次系统模式啊

**Comment by zui-lang** [comment]
> 目前只要开启了跟随系统，在打开应用时就会先检测一次系统模式啊

刚刚重新试了一下确实是可以的
