### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by xdd-0920** [imsyy/SPlayer#5]
你好，网站很喜欢，我部署后遇到跨域请求的问题，请问下这个代码怎么解决呀

**Comment by imsyy** [comment]
我的 api 开启了跨域限制，你可以尝试试用自己搭建的 api

**Comment by xdd501318235** [comment]
![image](https://user-images.githubusercontent.com/32973810/218264389-320f632d-1999-4df3-8c35-1ba335b5a5f8.png)
官网文档说是在调用的时候增加相关代码，是不是在调用时即SPlayer扫码时才可以解决

**Comment by imsyy** [comment]
> ![image](https://user-images.githubusercontent.com/32973810/218264389-320f632d-1999-4df3-8c35-1ba335b5a5f8.png)
> 官网文档说是在调用的时候增加相关代码，是不是在调用时即SPlayer扫码时才可以解决

这一点我已经做了处理了，你是用自己的 api 还跨域吗，报错截图瞅瞅

**Comment by xdd501318235** [comment]
![1676128137004](https://user-images.githubusercontent.com/32973810/218266054-63fd541c-f59a-4b4a-808e-d17b6226d93d.jpg)
用的是我自己的api，首页加载、播放歌曲都没问题，只有扫码登录会报错

**Comment by imsyy** [comment]
> ![1676128137004](https://user-images.githubusercontent.com/32973810/218266054-63fd541c-f59a-4b4a-808e-d17b6226d93d.jpg)
> 用的是我自己的api，首页加载、播放歌曲都没问题，只有扫码登录会报错

我的示例站点你能扫码登录嘛？
或者你也可以试试将 api 源码中的
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/server.js#L145-L145
加入自己的域名

**Comment by xdd501318235** [comment]
> > ![1676128137004](https://user-images.githubusercontent.com/32973810/218266054-63fd541c-f59a-4b4a-808e-d17b6226d93d.jpg)
> > 用的是我自己的api，首页加载、播放歌曲都没问题，只有扫码登录会报错
> 
> 我的示例站点你能扫码登录嘛？ 或者你也可以试试将 api 源码中的 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/server.js#L145-L145 加入自己的域名

示例网站我能扫码登录成功

**Comment by xdd501318235** [comment]
> > ![1676128137004](https://user-images.githubusercontent.com/32973810/218266054-63fd541c-f59a-4b4a-808e-d17b6226d93d.jpg)
> > 用的是我自己的api，首页加载、播放歌曲都没问题，只有扫码登录会报错
> 
> 我的示例站点你能扫码登录嘛？ 或者你也可以试试将 api 源码中的 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/server.js#L145-L145 加入自己的域名

![image](https://user-images.githubusercontent.com/32973810/218268282-61cc5f3c-7854-46bf-a6ea-dfe5817d1700.png)
扫码后调用api没有响应头
![image](https://user-images.githubusercontent.com/32973810/218268323-323e9dec-66da-4768-99cb-b72973401bef.png)
zhe'ge这个是预检的代码是有响应头的

**Comment by imsyy** [comment]
您好，请问问题解决了嘛 😂，你那边的网站我这访问不了
