### ISSUE TITLE
歌词界面触发位置

### ISSUE THREAD

**Issue by Jeamorg** [imsyy/SPlayer#58]
将打开歌词界面触发的位置（箭头所示位置）改为方框内，需要打开歌词界面时可以很方便且快速地打开
![Snipaste_2023-07-13_12-05-05](https://github.com/imsyy/SPlayer/assets/93057377/f52bab8c-181c-407a-8c7b-25171fe9595b)

**Comment by imsyy** [comment]
原来觉得容易误触就没加，可以自行改变点击事件的位置

**Comment by imsyy** [comment]
已增加该设置项
