### ISSUE TITLE
部署SSL证书后出现500错误

### ISSUE THREAD

**Issue by Alloy81284** [imsyy/SPlayer#69]
如题，无SSL情况下正常使用，部署了SSL后，访问https就会出现500错误，如果是http就正常使用

**Comment by imsyy** [comment]
api 的地址是 https 吗

**Comment by depression-hs** [comment]
> api 的地址是 https 吗

api也要添加ssl并且开启cdn吗，然后再给站点加上ssl开启cdn，这样就不会出现500的情况了吗

**Comment by imsyy** [comment]
> > api 的地址是 https 吗
> 
> api也要添加ssl并且开启cdn吗，然后再给站点加上ssl开启cdn，这样就不会出现500的情况了吗

是的，站点开启 https 后，api 也必须是 https，要不然会触发浏览器的安全机制，造成 CORS 问题
