### ISSUE TITLE
服务器错误，什么都加载不出

### ISSUE THREAD

**Issue by jianglizi** [imsyy/SPlayer#76]
![image](https://github.com/imsyy/SPlayer/assets/118318269/1b3a33df-f3e5-4c74-8f7f-0f20b09bd488)

**Comment by jianglizi** [comment]
大佬，你的演示端也是这样，怎么了

**Comment by imsyy** [comment]
检查你的api地址以及是否跨域，我演示站的api被调崩了，我给关了
