### ISSUE TITLE
网易云解灰失败

### ISSUE THREAD

**Issue by lazyingman** [imsyy/SPlayer#79]
本地部署的网易云解灰，代理用的我自己，但是有的时候会显示解灰成功，但是音乐不播放，把解灰项目部署到vercel上就直接用不了了，测试显示“Internal Server Error”，
但是本地会显示成功
![image](https://github.com/imsyy/SPlayer/assets/106133469/7f378643-5127-4da0-9601-9a4279bd2b13)
大佬这个是什么原因

**Comment by imsyy** [comment]
项目在重构了，后续会考虑其他方式来解决
