### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by youpingfang** [imsyy/SPlayer#82]
写个docker呢。直接部署坑太多了

**Comment by kokojacket** [comment]
+1

**Comment by imsyy** [comment]
@kokojacket @youpingfang 已支持

**Comment by kokojacket** [comment]
> @kokojacket @youpingfang 已支持

构建镜像失败,求个打包好的镜像
![image](https://github.com/imsyy/SPlayer/assets/74887370/d66dd455-e5c9-42d4-bdc7-009db632800c)

**Comment by imsyy** [comment]
> > @kokojacket @youpingfang 已支持
> 
> 构建镜像失败,求个打包好的镜像 ![image](https://private-user-images.githubusercontent.com/74887370/291829580-0968e79a-6dcf-4540-80ee-cb2800554c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE4MzEsIm5iZiI6MTcwMzA2MTUzMSwicGF0aCI6Ii83NDg4NzM3MC8yOTE4Mjk1ODAtMDk2OGU3OWEtNmRjZi00NTQwLTgwZWUtY2IyODAwNTU0YzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2Q4YzFjNzA0MTYyODM0MjM2NmE0NzhiNDNmM2JiNTE4YTU3Y2RiNjljOGQzODRjMjQ1NGNkNTIxOWI2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zo-bnnebcVWViuhficPH8nMAOgWqzWmx2nFU40nESWI)

拉取下最新版再试试

**Comment by kokojacket** [comment]
@imsyy 在dockerhub上找到了镜像，应该是大佬您构建的吧，我直接用这个了~

**Comment by imsyy** [comment]
是的，说明文档里有写的

**Comment by kokojacket** [comment]
hhhh一开始看还没有呢
热乎热乎~！！！
