### ISSUE TITLE
SPlayer-2.0.0-beta.1  运行pnpm dev时出错

### ISSUE THREAD

**Issue by blogclub** [imsyy/SPlayer#87]
SPlayer-2.0.0-beta.1

运行pnpm dev时出错：
/bin/sh: chcp: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

请问怎么解决？谢谢！

**Comment by imsyy** [comment]
先 npm i pnpm
