### ISSUE TITLE
关于验证码登录的疑问

### ISSUE THREAD

**Issue by kldhsh123** [imsyy/SPlayer#89]
我在翻源码时发现已经写了关于验证码登录的部分,并且网易云音乐API已经支持了,但是为什么最新版的SPlayer提示暂时无法使用呢？

**Comment by imsyy** [comment]
- `old` 分支的旧版本目前已经支持手机号登录
  ![image](https://github.com/imsyy/SPlayer/assets/42232682/8ea13445-6f2a-4ab1-b386-cc1418368f8f)

- 新版本即将支持

**Comment by kldhsh123** [comment]
您好,我下载了old版本,但是获取验证码输入点击登录没有反应,这种是什么情况呢？

**Comment by imsyy** [comment]
发下控制台的网络请求看下
