### ISSUE TITLE
PWA 支持

### ISSUE THREAD

**Issue by ssln5014** [imsyy/SPlayer#97]
### 希望添加什么功能？

加上PWA

### 具体信息

加两个文件就行了 [serviceWorker.js](https://github.com/ssln5014/SPlayer/commit/762b5b7755be532c4a96bab514bbb1a279c25d50)，[manifest.json](https://github.com/ssln5014/SPlayer/commit/4aa61b3f3d62de905de04d57f4a5454ebe3da80f)

**Comment by imsyy** [comment]
已支持
