### ISSUE TITLE
每日推荐打不开

### ISSUE THREAD

**Issue by 123123del** [imsyy/SPlayer#98]
### 是网页端还是客户端

客户端

### 当前系统环境

win11

### 当前 Node.js 及 npm 版本

v9.6.7

### 当前版本

v2.0.0-beta.4

### 具体信息

提示施工中（新建文件夹）

**Comment by imsyy** [comment]
功能目前未发布正式版

**Comment by 123123del** [comment]
好的，稳定版可以用吗

**Comment by imsyy** [comment]
beta.5 版本会上线的，可以等待日后的 2.0 正式版

**Comment by 123123del** [comment]
好的
