### ISSUE TITLE
Docker部署web端是否可以实现，一键下载至本机nas上

### ISSUE THREAD

**Issue by kokojacket** [imsyy/SPlayer#99]
### 希望添加什么功能？

远程下载至部署机

### 具体信息

Docker部署的web端，希望大佬能实现点击下载按钮不是保存到本地电脑，而是下载到nas机上
比如compsoe里添加一个挂载目录，然后选择下载目录为挂载目录

**Comment by imsyy** [comment]
这个恐怕实现不了，这本质上就是一个网页，而且这违背了这个功能的本意

**Comment by kokojacket** [comment]
好吧，目前有个小问题是，因为docker部署，无法设置下载位置，会一直弹出提示
![image](https://github.com/imsyy/SPlayer/assets/74887370/e2031bfb-3cfb-47e5-8f66-540a07b330a5)

**Comment by kokojacket** [comment]
@imsyy web端支持解灰了吗？似乎没有效果

**Comment by imsyy** [comment]
暂时还不支持，日后可能会支持

**Comment by kokojacket** [comment]
好的，大佬加油~！！
